baseURL = "/"
languageCode = "en-us"
title = "Yale Helix Site"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Website for Yale Helix, an undergraduate organization at Yale University."
    meta_og_title = "Yale Helix Site"
    meta_og_type = "website"
    meta_og_url = "https://yalehelix.com"
    meta_og_image = ""
    meta_og_description = "Website for Yale Helix, an undergraduate organization at Yale University."
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""



[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"